import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Toaster } from "@/components/ui/sonner";
import { AuthProvider } from "@/context/AuthContext";
import { WebsiteSettingsProvider } from "@/context/WebsiteSettingsContext";
import ConditionalLayout from "@/components/ConditionalLayout";
import ConsoleSuppress from "@/components/ConsoleSuppress";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          src="https://challenges.cloudflare.com/turnstile/v0/api.js"
          async
          defer
        ></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <AuthProvider>
          <WebsiteSettingsProvider>
            <ConsoleSuppress />
            <ConditionalLayout>
              {children}
            </ConditionalLayout>
            <Toaster position="top-center" />
          </WebsiteSettingsProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
